import { Artist, Deal } from '../types';

const getRelativeDate = (offsetDays: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString().split('T')[0];
};

export const initialArtists: Artist[] = [
  {
    id: 'art-1',
    name: 'Ken Carson (Opium)',
    instagram: 'https://instagram.com/kencarson',
    email: 'mgmt@kencarson.com',
    phone: '+1 404 555 0192',
    telegram: '@opium_mgmt_atl',
    discord: 'kencarson#0001',
    notes: 'Likes fast 145+ BPM synth rage beats with gritty distorted 808s. Sent pack "AGC_VIBES_2026.zip".',
    connect: 'yes',
    types: ['Ken Carson', 'Dark Rage', 'Opium', 'Distorted 808'],
    sales: 'yes',
    status: 'active',
    demoStatus: 'liked',
    touches: 4,
    reaction: 'wants_more',
    followUpDate: getRelativeDate(0), // Today!
    lastContactDate: getRelativeDate(-1),
    isDeleted: false,
    createdAt: '2026-08-10',
    updatedAt: '2026-08-30',
  },
  {
    id: 'art-2',
    name: 'Destroy Lonely',
    instagram: 'https://instagram.com/destroylonely',
    email: 'lone@opiumrecords.net',
    phone: '+1 404 555 8821',
    telegram: '@lookkilla_lone',
    discord: 'destroylonely',
    notes: 'Prefers ambient guitar samples and heavy sub-bass. Discussing exclusive license for 2 tracks.',
    connect: 'yes',
    types: ['Destroy Lonely', 'Ambient Trap', 'Opium', 'Guitar'],
    sales: 'yes',
    status: 'active',
    demoStatus: 'in_progress',
    touches: 5,
    reaction: 'ready_to_buy',
    followUpDate: getRelativeDate(2),
    lastContactDate: getRelativeDate(-2),
    isDeleted: false,
    createdAt: '2026-08-12',
    updatedAt: '2026-08-29',
  },
  {
    id: 'art-3',
    name: 'Yeat (Twizzy)',
    instagram: 'https://instagram.com/yeat',
    email: 'packforyeat@twizzyrich.com',
    phone: '+1 310 555 7714',
    telegram: '@yeat_submissions',
    discord: 'twizzy_rich',
    notes: 'Needs bell-heavy energetic rage with hyperactive hi-hats. Producer tag must be subtle.',
    connect: 'yes',
    types: ['Yeat', 'Hyperpop', 'Bell Rage', 'Synth'],
    sales: 'no',
    status: 'active',
    demoStatus: 'sent',
    touches: 2,
    reaction: 'listening',
    followUpDate: getRelativeDate(-2), // Overdue!
    lastContactDate: getRelativeDate(-3),
    isDeleted: false,
    createdAt: '2026-08-15',
    updatedAt: '2026-08-27',
  },
  {
    id: 'art-4',
    name: 'Osamason (Flexxx)',
    instagram: 'https://instagram.com/osamason',
    email: 'osamabusiness@gmail.com',
    phone: '+1 843 555 4910',
    telegram: '@osamason_official',
    discord: 'osamason_flx',
    notes: 'Loves raw underground pluggnb / filthy distortion. Asked for trackouts on 1 beat.',
    connect: 'yes',
    types: ['Osamason', 'Filthy', 'Dark Rage', 'Underground'],
    sales: 'yes',
    status: 'active',
    demoStatus: 'liked',
    touches: 3,
    reaction: 'ready_to_buy',
    followUpDate: getRelativeDate(1),
    lastContactDate: getRelativeDate(0),
    isDeleted: false,
    createdAt: '2026-08-18',
    updatedAt: '2026-08-30',
  },
  {
    id: 'art-5',
    name: 'Playboi Carti A&R',
    instagram: 'https://instagram.com/opium_00',
    email: 'carti_a_r@interscope.com',
    phone: '+1 212 555 0118',
    telegram: '@opium_ar_team',
    discord: '',
    notes: 'Sent 10 beat snippets in Google Drive folder. Waiting for A&R feedback on "MUSIC" rollout.',
    connect: 'no',
    types: ['Carti', 'Dark Synth', 'Experimental', 'Industrial'],
    sales: 'no',
    status: 'passive',
    demoStatus: 'sent',
    touches: 1,
    reaction: 'ignored',
    followUpDate: getRelativeDate(-5), // Overdue!
    lastContactDate: getRelativeDate(-14),
    isDeleted: false,
    createdAt: '2026-08-01',
    updatedAt: '2026-08-20',
  },
  {
    id: 'art-6',
    name: 'Lil Tecca',
    instagram: 'https://instagram.com/liltecca',
    email: 'tecca.beats@galacticsounds.com',
    phone: '+1 646 555 9301',
    telegram: '@teccaboy',
    discord: 'tecca_beats',
    notes: 'Looking for melodic bouncy summer beats with catchy flute/keys.',
    connect: 'yes',
    types: ['Lil Tecca', 'Melodic Trap', 'Bounce', 'Flute'],
    sales: 'no',
    status: 'active',
    demoStatus: 'liked',
    touches: 3,
    reaction: 'replied',
    followUpDate: getRelativeDate(3),
    lastContactDate: getRelativeDate(-1),
    isDeleted: false,
    createdAt: '2026-08-22',
    updatedAt: '2026-08-29',
  },
  {
    id: 'art-7',
    name: 'Homixide Gang (Meechie & Beno)',
    instagram: 'https://instagram.com/homixidegang',
    email: 'hxglive@gmail.com',
    phone: '+1 404 555 3309',
    telegram: '@hxg_official',
    discord: 'hxg_5',
    notes: 'Fast drill / rage hybrid with aggressive 808 slides. Sent pack #5.',
    connect: 'yes',
    types: ['Homixide Gang', 'Dark Rage', 'Drill Hybrid', 'Distorted 808'],
    sales: 'yes',
    status: 'active',
    demoStatus: 'liked',
    touches: 4,
    reaction: 'wants_more',
    followUpDate: getRelativeDate(0), // Today!
    lastContactDate: getRelativeDate(0),
    isDeleted: false,
    createdAt: '2026-08-05',
    updatedAt: '2026-08-31',
  },
  {
    id: 'art-8',
    name: 'Lazer Dim 700',
    instagram: 'https://instagram.com/lazerdim700',
    email: 'lazerdim700mgmt@gmail.com',
    phone: '+1 470 555 7712',
    telegram: '@lazerdim700',
    discord: '',
    notes: 'Raw off-beat tempo switches, dirty 808 bass, short 1:30 track structure.',
    connect: 'no',
    types: ['Lazer Dim 700', 'Raw Atlanta', 'Underground', 'Dark Rage'],
    sales: 'no',
    status: 'passive',
    demoStatus: 'none',
    touches: 0,
    reaction: 'none',
    followUpDate: getRelativeDate(4),
    lastContactDate: '',
    isDeleted: false,
    createdAt: '2026-08-25',
    updatedAt: '2026-08-25',
  },
  {
    id: 'art-9',
    name: 'Nettspend',
    instagram: 'https://instagram.com/nettspend',
    email: 'nettspendva@gmail.com',
    phone: '+1 804 555 2290',
    telegram: '@nettspendva',
    discord: 'nettspend',
    notes: 'Jerkin style + nostalgic 2010s vocal chops & reverb kicks. Hit him on iMessage.',
    connect: 'yes',
    types: ['Nettspend', 'Jerkin', 'Nostalgic', 'Sample Drill'],
    sales: 'no',
    status: 'active',
    demoStatus: 'sent',
    touches: 2,
    reaction: 'listening',
    followUpDate: getRelativeDate(-1), // Overdue!
    lastContactDate: getRelativeDate(-5),
    isDeleted: false,
    createdAt: '2026-08-16',
    updatedAt: '2026-08-28',
  },
  {
    id: 'art-10',
    name: 'Hardrock',
    instagram: 'https://instagram.com/hardrock',
    email: 'hardrockmgmt@1of1.com',
    phone: '+1 404 555 8899',
    telegram: '@hardrock_atl',
    discord: '',
    notes: 'Atmospheric Pierre / ethereal synth chords with rolling hi-hats. DM seen.',
    connect: 'no',
    types: ['Hardrock', 'Ethereal Trap', 'Pierre Chords', 'Ambient Synth'],
    sales: 'no',
    status: 'active',
    demoStatus: 'sent',
    touches: 1,
    reaction: 'replied',
    followUpDate: getRelativeDate(1),
    lastContactDate: getRelativeDate(-8),
    isDeleted: false,
    createdAt: '2026-08-20',
    updatedAt: '2026-08-28',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-1',
    artistId: 'art-1',
    artistName: 'Ken Carson (Opium)',
    platform: 'iMessage',
    stage: 'closed',
    amount: 750,
    currency: '$',
    date: '2026-08-24',
    notes: 'Exclusive license for track "Vampire Teeth" (WAV + Stems + 50/50 publishing rights). Paid via Stripe.',
    createdAt: '2026-08-20',
    updatedAt: '2026-08-24',
  },
  {
    id: 'deal-2',
    artistId: 'art-2',
    artistName: 'Destroy Lonely',
    platform: 'Instagram',
    stage: 'in_progress',
    amount: 500,
    currency: '$',
    date: '2026-08-29',
    notes: '2 Unlimited Leases. Waiting for contract sign & signature on Split Sheet.',
    createdAt: '2026-08-28',
    updatedAt: '2026-08-30',
  },
  {
    id: 'deal-3',
    artistId: 'art-4',
    artistName: 'Osamason (Flexxx)',
    platform: 'Telegram',
    stage: 'interested',
    amount: 300,
    currency: '$',
    date: '2026-08-30',
    notes: 'Wants exclusive for upcoming mixtape track. Sent invoice preview.',
    createdAt: '2026-08-30',
    updatedAt: '2026-08-31',
  },
  {
    id: 'deal-4',
    artistId: 'art-7',
    artistName: 'Homixide Gang (Meechie & Beno)',
    platform: 'Instagram',
    stage: 'closed',
    amount: 450,
    currency: '$',
    date: '2026-08-15',
    notes: 'WAV Lease for "5TH_GEN_RAGE". Producer credit in metadata confirmed.',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-15',
  },
  {
    id: 'deal-5',
    artistId: 'art-6',
    artistName: 'Lil Tecca',
    platform: 'Email',
    stage: 'in_progress',
    amount: 1200,
    currency: '$',
    date: '2026-08-31',
    notes: 'Album placement negotiation (Co-prod with Internet Money producer).',
    createdAt: '2026-08-29',
    updatedAt: '2026-08-31',
  },
];
