import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(10000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'artifacts/artists-light.png', fullPage: true });
console.log('Initial theme:', await page.locator('html').getAttribute('class'));
for (const tab of ['deals', 'analytics', 'parser']) {
  await page.locator('.studio-nav-item').nth(['artists', 'deals', 'analytics', 'parser'].indexOf(tab)).click();
  await page.waitForTimeout(650);
  await page.screenshot({ path: `artifacts/${tab}-light.png`, fullPage: true });
  console.log(tab, await page.locator('h1').first().textContent());
}
await page.locator('.studio-nav-item').first().click();
await page.locator('#add-artist-primary-btn').click();
await page.waitForTimeout(650);
await page.screenshot({ path: 'artifacts/artist-modal.png', fullPage: true });
await page.keyboard.press('Escape');
await page.locator('#theme-toggle-btn').click();
await page.waitForTimeout(350);
await page.screenshot({ path: 'artifacts/artists-dark.png', fullPage: true });
await page.locator('#theme-toggle-btn').click();
await page.waitForTimeout(350);
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.locator('.studio-nav-item').nth(2).click();
await page.getByRole('button', { name: 'Загрузить демо-данные', exact: true }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: 'artifacts/analytics-data.png', fullPage: true });
await page.locator('.studio-nav-item').first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: 'artifacts/artists-data.png', fullPage: true });
const before = await page.locator('tbody tr').count();
await page.locator('#global-search-input').fill('Ken Carson');
await page.waitForTimeout(250);
const after = await page.locator('tbody tr').count();
if (!(before > after && after > 0)) throw new Error('Search did not filter rows');
await page.locator('#global-search-input').fill('');
await page.locator('[data-quick-filter]').first().click();
if (await page.locator('[data-quick-filter]').first().getAttribute('aria-pressed') !== 'true') throw new Error('Filter not active');
await page.locator('[data-quick-filter]').first().click();
await page.locator('#theme-toggle-btn').click();
await page.waitForTimeout(650);
await page.screenshot({ path: 'artifacts/artists-data-dark.png', fullPage: true });
await page.locator('.studio-nav-item').nth(1).click();
await page.waitForTimeout(300);
await page.screenshot({ path: 'artifacts/deals-data-dark.png', fullPage: true });
await page.locator('#add-deal-primary-btn').click();
await page.waitForTimeout(650);
await page.screenshot({ path: 'artifacts/deal-modal-dark.png', fullPage: true });
await page.keyboard.press('Escape');
await page.waitForTimeout(350);
if (await page.locator('.studio-dialog').count()) throw new Error('Dialog did not unmount after exit');
await page.locator('.studio-nav-item').first().click();
await page.waitForTimeout(650);
await page.getByText('Ken Carson (Opium)', { exact: true }).click();
await page.locator('.native-drawer').waitFor({ state: 'visible' });
await page.waitForTimeout(650);
await page.screenshot({ path: 'artifacts/native-drawer.png', fullPage: true });
await page.keyboard.press('Escape');
await page.waitForTimeout(350);
if (await page.locator('.native-drawer').count()) throw new Error('Drawer did not unmount after exit');
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.locator('#add-artist-primary-btn').click();
await page.waitForTimeout(300);
console.log('Reduced-motion dialog transform:', await page.locator('.studio-dialog').evaluate(el => getComputedStyle(el).transform));
await page.keyboard.press('Escape');
await page.waitForTimeout(350);
console.log('Font:', await page.locator('h1').evaluate(el => getComputedStyle(el).fontFamily));
console.log('Search, filters, modal/drawer transitions and reduced motion passed:', before, '->', after);
console.log('Page errors:', errors);
console.log('Mobile overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
await browser.close();
if (errors.length) process.exitCode = 1;
